### ISSUE TITLE
Adding a pattern validation causes exception

### ISSUE THREAD

**Issue by awillemsen** [eclipse-emfcloud/emfcloud-modelserver#102]
Adding a pattern validation causes the following exception when running the "validation" endpoint:

java.lang.IllegalArgumentException: No serializer found for class org.eclipse.emf.ecore.xml.type.util.XMLTypeUtil$PatternMatcherImpl and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.Collections$UnmodifiableRandomAccessList[0]->java.util.Collections$UnmodifiableRandomAccessList[0]->org.eclipse.emf.common.util.BasicEList$UnmodifiableEList[2]->org.eclipse.emf.ecore.xml.type.util.XMLTypeUtil$PatternMatcherImpl[0])
        at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2978)
        at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelValidator.validate(DefaultModelValidator.java:63)
        at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelController.validate(DefaultModelController.java:213)
        at org.eclipse.emfcloud.modelserver.emf.common.ModelServerRoutingV1.lambda$23(ModelServerRoutingV1.java:138)
        at java.base/java.util.Optional.ifPresentOrElse(Optional.java:201)
        at org.eclipse.emfcloud.modelserver.emf.common.ModelServerRoutingV1.validateModel(ModelServerRoutingV1.java:137)
        at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:23)
        at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet.kt:121)
        at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:45)
        at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:24)
        at io.javalin.http.JavalinServlet$service$1.invoke(JavalinServlet.kt:129)
        at io.javalin.http.JavalinServlet$service$2.invoke(JavalinServlet.kt:40)
        at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:81)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.javalin.websocket.JavalinWsServlet.service(JavalinWsServlet.kt:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at io.javalin.core.JavalinServer$start$wsAndHttpHandler$1.doHandle(JavalinServer.kt:49)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.eclipse.emf.ecore.xml.type.util.XMLTypeUtil$PatternMatcherImpl and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.Collections$UnmodifiableRandomAccessList[0]->java.util.Collections$UnmodifiableRandomAccessList[0]->org.eclipse.emf.common.util.BasicEList$UnmodifiableEList[2]->org.eclipse.emf.ecore.xml.type.util.XMLTypeUtil$PatternMatcherImpl[0])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
        at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191)
        at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:404)
        at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71)
        at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33)
        at com.fasterxml.jackson.databind.ser.std.ObjectArraySerializer.serializeContents(ObjectArraySerializer.java:252)
        at com.fasterxml.jackson.databind.ser.std.ObjectArraySerializer.serialize(ObjectArraySerializer.java:213)
        at com.fasterxml.jackson.databind.ser.std.ObjectArraySerializer.serialize(ObjectArraySerializer.java:22)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2804)
        at com.fasterxml.jackson.databind.util.TokenBuffer.writeObject(TokenBuffer.java:936)
        at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1769)
        at org.eclipse.emfcloud.modelserver.emf.common.ValidationMapperModule$BasicDiagnosticSerializer.serialize(ValidationMapperModule.java:78)
        at org.eclipse.emfcloud.modelserver.emf.common.ValidationMapperModule$BasicDiagnosticSerializer.serialize(ValidationMapperModule.java:1)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2804)
        at com.fasterxml.jackson.databind.util.TokenBuffer.writeObject(TokenBuffer.java:936)
        at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1769)
        at org.eclipse.emfcloud.modelserver.emf.common.ValidationMapperModule$BasicDiagnosticSerializer.serialize(ValidationMapperModule.java:79)
        at org.eclipse.emfcloud.modelserver.emf.common.ValidationMapperModule$BasicDiagnosticSerializer.serialize(ValidationMapperModule.java:1)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2804)
        at com.fasterxml.jackson.databind.util.TokenBuffer.writeObject(TokenBuffer.java:936)
        at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1769)
        at org.eclipse.emfcloud.modelserver.emf.common.ValidationMapperModule$BasicDiagnosticSerializer.serialize(ValidationMapperModule.java:79)
        at org.eclipse.emfcloud.modelserver.emf.common.ValidationMapperModule$BasicDiagnosticSerializer.serialize(ValidationMapperModule.java:1)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2804)
        at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2973)
        ... 44 more

The following changes were done to the Coffee model:

```
  <eClassifiers xsi:type="ecore:EClass" name="Machine" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="#//String3Chars"/>

  <eClassifiers xsi:type="ecore:EDataType" name="String3Chars" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="maxLength" value="3"/>
      <details key="pattern" value="[A-Z0-9_]+"/>
    </eAnnotations>
  </eClassifiers>
```

And the following model resource was created:

{
  "eClass" : "http://www.eclipsesource.com/modelserver/example/coffeemodel#//Machine",
  "name" : "hello"
}

Without the pattern validation, the "validation" endpoint successfully completed, and reported that the name "hello" was too long.  However, with the pattern validation, the above exception was raised.

**Comment by awillemsen** [comment]
Changes to Coffee model:

`
  <eClassifiers xsi:type="ecore:EClass" name="Machine" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="#//String3Chars"/>

  <eClassifiers xsi:type="ecore:EDataType" name="String3Chars" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="maxLength" value="3"/>
      <details key="pattern" value="[A-Z0-9_]+"/>
    </eAnnotations>
  </eClassifiers>
`

**Comment by sgraband** [comment]
Thanks for reporting this @awillemsen! 
I am able to reproduce it. It seems that this is only happening if the `pattern` facet is set. The other facets seem to be fine. So there is probably a difference in the produced diagnostic or the format of the pattern is breaking the json mapper. 
I will look into it.
