### ISSUE TITLE
API V2: rewritePathsAsURIFragments doesn't (always?) work for deleted elements

### ISSUE THREAD

**Issue by CamilleLetavernier** [eclipse-emfcloud/emfcloud-modelserver#218]
When sending a Json Patch reply to a client, we sometimes rewrite the result path as an EMF-Like path (When the client requests this format).

However, Json Paths may represent objects that no longer exist (e.g. deleted index), which can't be properly rewritten as EMF URIs (Since deleted objects no longer have a URI in EMF). In that case, we get an exception. For example, after Undoing the creation of a new element):

```
58844 [JettyServerThreadPool-24] ERROR org.eclipse.emfcloud.modelserver.emf.common.SingleThreadModelController [] - Execution Exception
java.util.concurrent.ExecutionException: org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=4, size=4
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:205) ~[?:?]
	at org.eclipse.emfcloud.modelserver.emf.common.SingleThreadModelController.waitComplete(SingleThreadModelController.java:225) ~[classes/:?]
	at org.eclipse.emfcloud.modelserver.emf.common.SingleThreadModelController.runAndWait(SingleThreadModelController.java:219) ~[classes/:?]
	at org.eclipse.emfcloud.modelserver.emf.common.SingleThreadModelController.undo(SingleThreadModelController.java:175) ~[classes/:?]
	at org.eclipse.emfcloud.modelserver.emf.common.ModelServerRoutingDelegate.lambda$8(ModelServerRoutingDelegate.java:151) ~[classes/:?]
	at java.util.Optional.ifPresentOrElse(Optional.java:196) ~[?:?]
	at org.eclipse.emfcloud.modelserver.emf.common.ModelURIConverter.withResolvedModelURI(ModelURIConverter.java:100) ~[classes/:?]
	at org.eclipse.emfcloud.modelserver.emf.common.ModelURIConverter.withResolvedModelURI(ModelURIConverter.java:154) ~[classes/:?]
	at org.eclipse.emfcloud.modelserver.emf.common.ModelServerRoutingDelegate.undoCommand(ModelServerRoutingDelegate.java:151) ~[classes/:?]
	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20) ~[javalin-4.3.0.jar:4.3.0]
	[...]
Caused by: org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=4, size=4
	at org.eclipse.emf.common.util.BasicEList.get(BasicEList.java:346) ~[org.eclipse.emf.common_2.24.0.v20220123-0838.jar:?]
	at org.eclipse.emfcloud.modelserver.common.patch.AbstractJsonPatchHelper.getValueFromList(AbstractJsonPatchHelper.java:576) ~[classes/:?]
	at org.eclipse.emfcloud.modelserver.common.patch.AbstractJsonPatchHelper.getSettingFromJsonPointer(AbstractJsonPatchHelper.java:484) ~[classes/:?]
	at org.eclipse.emfcloud.modelserver.emf.util.JsonPatchHelper.getSetting(JsonPatchHelper.java:50) ~[classes/:?]
	at org.eclipse.emfcloud.modelserver.emf.util.JsonPatchHelper.toURIFragmentPath(JsonPatchHelper.java:258) ~[classes/:?]
	at org.eclipse.emfcloud.modelserver.emf.util.JsonPatchHelper.lambda$1(JsonPatchHelper.java:241) ~[classes/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at org.eclipse.emfcloud.modelserver.emf.util.JsonPatchHelper.toURIFragmentPath(JsonPatchHelper.java:240) ~[classes/:?]
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultSessionController.resolvePathAsURIFragment(DefaultSessionController.java:303) ~[classes/:?]
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultSessionController.rewritePathsAsURIFragments(DefaultSessionController.java:294) ~[classes/:?]
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultSessionController.lambda$4(DefaultSessionController.java:277) ~[classes/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3573) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultSessionController.broadcastIncrementalUpdatesV2(DefaultSessionController.java:275) ~[classes/:?]
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultSessionController.broadcastIncrementalUpdatesV2(DefaultSessionController.java:200) ~[classes/:?]
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultSessionController.commandExecuted(DefaultSessionController.java:176) ~[classes/:?]
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelController.lambda$1(DefaultModelController.java:273) ~[classes/:?]
	at java.util.Optional.ifPresentOrElse(Optional.java:196) ~[?:?]
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelController.lambda$0(DefaultModelController.java:261) ~[classes/:?]
	at java.util.Optional.ifPresentOrElse(Optional.java:196) ~[?:?]
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelController.withModel(DefaultModelController.java:413) ~[classes/:?]
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelController.undo(DefaultModelController.java:260) ~[classes/:?]
	[...]
```

The Json Path to rewrite:

```json
{"op":"remove","path":"/components/4"}
```

**Comment by CamilleLetavernier** [comment]
Note: part of the issue could related to how the server decides to rewrite Json Paths. It isn't an explicit parameter used by the client for the request. Instead, it is derived from the Patch path (if the Patch uses an EMF URI, then the reply will also be rewritten with EMF URIs), which doesn't always make sense.

Many clients use Operations built from the API, which always use EMF-like paths, because it's a lot easier (we just have to read the $id or $ref attribute of the single object we want to edit, and we don't have to worry about the general context, i.e. where this object is located in the tree). However, we don't necessarily want the symmetric behavior for the reply, as this creates a Patch that can't be applied by Json Patch libraries; so the only thing we can do with rewritten patches is to "parse" them manually - or to completely ignore them.

While URI rewriting makes sense in some cases (because Json Patch results don't provide any context), I think it should be an explicitly request from the client (e.g. with a query parameter). So there are 2 issues here:

- rewritePathsAsURIFragments shouldn't cause exceptions
- URIs shouldn't be rewritten at all without the client explicitly requesting it

Regarding rewritePathsAsURIFragments, I'm not sure how to properly handle deleted objects, where Json Paths and EMF URIs are not equivalent. Do we want to keep the original Json Path in that case? Or do we want something more complex, that would retrieve the former URI of the object that was deleted? (Which may not be possible at the time where the Json Path is being rewritten, because the object is already deleted and no longer has a URI; so we might need to derive the URI while reverting the transaction).

@cdamus WDYT?

**Comment by cdamus** [comment]
In fact, wouldn't a patch operation targeting a deleted object be inapplicable anyways and cause the patch to fail? Even with a JSON Pointer `path`. The object isn't there to apply the operation to it.

**Comment by CamilleLetavernier** [comment]
This isn't about patching elements that were deleted; this is about the patch that describes the changes that have been applied (Sent to subcribers)

So if you have a list of 3 elements, and delete the element at index 2, you end up with this patch:

```json
{"op": "remove", "path":"elements/2"}
```
This describes the change; but when converting "elements/2" to an EMF URI *after* the patch has been applied, then this object no longer exists, and the conversion to an EMF URI fails (There is no object with index "2" anymore).

This is still a valid patch for the client (because it doesn't know how the model has changed just yet, so it still has an object at index 2), but not for the server (and it's also not valid for the method that rewrites Json Path to EMF URI, because it works with the updated model).

**Comment by CamilleLetavernier** [comment]
```
But I'm not sure that we have a general way to do this without analyzing up-front the command or patch that causes an object to be deleted.
```

Yeah. In the general case, it might even be more complicated than that, for large patches that affect multiple objects: the path used by a Json patch Operation N refers to the intermediate state, resulting of the application of operation N-1. So from an empty list, you can specify e.g. [add /0, add /1, add /2, add /3] and that's a valid patch (even though none of these indices exist when creating the patch)

In that case, neither the initial model state nor the final model state if a valid referential for this patch.

We could even imagine weird cases such as:

[add /0, remove /0], which creates and immediately deletes an object, so it won't exist in the initial state nor in the final state (But in that case, the resulting patch obtained by diff'ing the initial and final model would be empty, so we probably don't have to worry about such a case).

Anyway: converting Json Path to EMF URI isn't trivial. We should at least make sure that it doesn't break. When we can't generate a valid EMF-like path, we need a generic fall back (and then the client can be responsible for fetching the entire model if it can't interpret the incremental patch, or something like that)

**Comment by cdamus** [comment]
> Yeah. In the general case, it might even be more complicated than that, for large patches that affect multiple objects: the path used by a Json patch Operation N refers to the intermediate state, resulting of the application of operation N-1. So from an empty list, you can specify e.g. [add /0, add /1, add /2, add /3] and that's a valid patch (even though none of these indices exist when creating the patch)

Right. In general, applications cannot assume that operations in a patch can be applied in arbitrary order. They are definitely an ordered sequence!

> [add /0, remove /0], which creates and immediately deletes an object, so it won't exist in the initial state nor in the final state (But in that case, the resulting patch obtained by diff'ing the initial and final model would be empty, so we probably don't have to worry about such a case).

I would expect so, yes. This should have no trace in the delta notification.

**Comment by cdamus** [comment]
In thinking about this problem more, I'm confused, again. In the original example:

```json
{ "op": "remove", "path":"/components/4" }
```

a value is removed from the 4th slot in the `components` array of the root object (whose path is `/`). This object still exists in the model after the diff. In fact, every object that owns a property identified by the `path` of an operation in the patch (diff) still exists in the model. Otherwise, it couldn't appear in the diff. In this case, the EMF-ish URI-based path would be like

```json
{ "op": "remove", "path": "file:/home/tester/models/resource.xmi#_0x7a57e5600d/components/4" }
```

where the EMF URI part of the `path` identifies the model root object.

A more deeply nested example makes it more clear. With a standard JSON pointer, this:

```json
{ "op": "remove", "path":"/components/4/things/1/head" }
```

in which an object is removed from a single-valued feature `head` of a `Thing` inside a `Component`, might transform to:

```json
{ "op": "remove", "path":"file:/home/tester/models/resource.xmi#_0x157a57y/head" }
```

where the EMF URI part of the `path` identifies a more deeply nested object than the root. But that object must still exist in the model in the "after" state because otherwise there wouldn't be operations describing changes of its properties; there would only be some operation that implies its own removal. This is only true because the diff-patch is created by a static comparison of the before and after states of the model; it has no knowledge of any intermediate states of the model that may have been described by the original edit-patch.

So, now I'm thinking that we were actually calculating the wrong "URI-ish paths" all along. That we were not properly converting only the "owner" portion of the `path` pointer to an EMFish URI, but sometimes took the whole `path` as the "URI", such as might seem to make sense for a `remove` operation.
